---

- hosts: localhost
  #sudo: no
  gather_facts: no
  tasks:
    - include: tasks/main.yml
    - include: tasks/profile.yml
    - include: tasks/software.yml
    - include: tasks/go.yml
    - include: tasks/vim.yml
