---

- hosts: localhost
  #sudo: no
  vars:
    user_home: "{{ lookup('env', 'HOME') }}"
  gather_facts: no
  tasks:
    - include: tasks/main.yml
    - include: tasks/profile.yml
    - include: tasks/software.yml
    #- include: tasks/go.yml
    #- include: tasks/vim.yml
