---

- name: Go workspace
  shell: mkdir -p ~/go/{{item}}
  args:
    creates: /usr/local/bin/brew
  with_items:
    - src
  tags:
    - go


- name: Go tools
  command: go get -u {{ item }}
  args:
    creates: ~/go/src/{{item}}
  with_items:
    - github.com/golang/lint/golint
    - github.com/shurcooL/markdownfmt
    # For deoplete-go completion
    - github.com/nsf/gocode
  tags:
    - go
