---

- name: Bash profile
  copy:
    src: "{{ item }}"
    dest: "~/{{ item }}"
    mode: 0600
    backup: yes
  with_items:
    - .bash_profile
    - .bash_prompt
    - .dockerfunc
    - .bashrc
    - .exports
    - .aliases
    - .path
    - .gitconfig
    - .gitignore_global
  tags:
    - profile
