---

# http://brew.sh/
- name: Brew
  shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  args:
    creates: /usr/local/bin/brew
  tags:
    - software

- name: Java
  command: /usr/local/bin/brew cask install java
  args:
    creates: /usr/bin/java
  tags:
    - software

- name: Brew software
  command: /usr/local/bin/brew install {{ item }} creates=/usr/local/bin/{{ item }}
  with_items:
    - git
    - go
    - gradle
    - jq
    - kafkacat
    - nload
    - nmap
    - node
    - openconnect
    - python
    - python3
    - sbt
    - tree
    - watch
    - wget
    - bash-completion
  tags:
    - software


