---

# http://brew.sh/
- name: Brew
  shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  args:
    creates: /usr/local/bin/brew
  tags:
    - software

- name: Sdkman
  shell: curl -s "https://get.sdkman.io" | bash
  args:
    creates: "{{ user_home }}/.sdkman"
  tags:
    - software
    - java
  register: sdkman

- name: Java 
  when: sdkman is succeeded
  shell: source "{{ user_home }}/.sdkman/bin/sdkman-init.sh" && sdk install java {{ item }}
  args:
    creates: "{{ user_home }}/.sdkman/candidates/java/{{ item }}"
  with_items:
    - 8.0.292.hs-adpt
  tags:
    - software
    - java

- name: Brew software
  command: /usr/local/bin/brew install {{ item }} creates=/usr/local/bin/{{ item }}
  with_items:
    - bash-completion
    - dep
    - git
    - go
    - gradle
    - htop 
    - jq
    - kafkacat
    - maven
    - nload
    - nmap
    - node
    - openconnect
    - protobuf
    - pt
    - s3cmd
    - socat
    - sbt
    - telnet
    - tree
    - watch
    - wget
  tags:
    - software
    - cli

- name: Brew Cask Software
  command: /usr/local/bin/brew install {{ item.name }}
  args:
    creates: /Applications/{{ item.app }}.app
  with_items:
    - name: docker
      app: Docker
    - name: spectacle
      app: Spectacle
    - name: slack
      app: Slack
    - name: visual-studio-code
      app: Visual Studio Code
  tags:
    - software
