---

# http://brew.sh/
- name: Brew
  shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  args:
    creates: /usr/local/bin/brew
  tags:
    - software

- name: Java
  command: /usr/local/bin/brew cask install java
  args:
    creates: /usr/bin/java
  tags:
    - software

- name: Brew software
  command: /usr/local/bin/brew install {{ item }} creates=/usr/local/bin/{{ item }}
  with_items:
    - bash-completion
    - git
    - go
    - gradle
    - htop
    - jq
    - kafkacat
    - maven
    - nload
    - nmap
    - node
    - openconnect
    - pt
    - python
    - python3
    - sbt
    - tree
    - watch
    - wget
  tags:
    - software
    - cli

- name: Brew Cask Software
  command: /usr/local/bin/brew cask install {{ item.name }}
  args:
    creates: /Applications/{{ item.app }}.app
  with_items:
    - name: docker
      app: Docker
    - name: spectacle
      app: Spectacle
    - name: slack
      app: Slack
    - name: iterm2
      app: iTerm
  tags:
    - software
