---

# Ref: https://github.com/fatih/vim-go-tutorial

- name: neo-vim
  shell: brew tap neovim/neovim && brew install neovim
  args:
    creates: /usr/local/Cellar/neovim
  tags:
    - vim

# Required for deoplete autocompletion
- name: neo-vim python packages
  command: "{{ item }} install --user neovim"
  with_items:
    - pip2
    - pip3
  tags:
    - vim

- name: create dirs
  file: path="{{ item }}" state=directory mode=0755
  with_items:
    - ~/.vim/autoload
    - ~/.vim/colors
    - ~/.config/nvim/autoload
  tags:
    - vim

- name: vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ item }}"
    mode: 0440
  with_items:
    - ~/.vim/autoload/plug.vim
    - ~/.config/nvim/autoload/plug.vim
  tags:
    - vim

- name: vim-go
  git:
    repo: https://github.com/fatih/vim-go.git
    dest: ~/.vim/plugged/vim-go
    update: no
  tags:
    - vim

- name: ansible-vim
  git:
    repo: https://github.com/pearofducks/ansible-vim.git
    dest: ~/.vim/plugged/ansible-vim
    update: no
  tags:
    - vim

- name: vim-dispatch
  git:
    repo: git://github.com/tpope/vim-dispatch.git
    dest: ~/.vim/plugged/vim-dispatch
    update: no
  tags:
    - vim

- name: check for molokai color scheme
  stat: path=~/.vim/colors/molokai.vim
  register: download_molokai
  tags:
    - vim

- name: download molokai color scheme
  when: not download_molokai.stat.exists
  git:
    repo: git://github.com/tomasr/molokai.git
    dest: /tmp/molokai
    update: no
  register: install_molokai
  tags:
    - vim

- name: install molokai color scheme
  when: install_molokai is defined
  copy:
    src: /tmp/molokai/colors/molokai.vim
    dest: ~/.vim/colors/molokai.vim
  tags:
    - vim

- name: .vimrc
  copy:
    src: .vimrc
    dest: ~/.vimrc
    mode: 0600
    backup: yes
  tags:
    - vim
    - vimrc

- name: neovim init.vim symlink
  file:
    src: ~/.vimrc
    path: ~/.config/nvim/init.vim
    state: link
  tags:
    - vim
